name: CodeEdit Issues
on:
  issues:
    types:
      - opened

jobs:
  codeEditIssues:
    runs-on: ubuntu-latest
    steps:
      - uses: nanashili/CodeEdit-Github-Action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
